#!/bin/bash
#
# Usage: compilete [name of .te file in current directory]
#
cleanName=$(echo $1 | sed s/\.te//g)
checkmodule -M -m -o $cleanName.mod $1
semodule_package -o $cleanName.pp -m $cleanName.mod
